// Mock data for the PDV
window.PDV_DATA = {
  user: {
    name: 'Arthur Caleb Souza Nunes',
    role: 'Vendedor',
    initials: 'AC',
    shift: 'Caixa 02',
  },
  today: {
    date: 'Sáb, 09 de Maio',
    fullDate: '2026-05-09',
    sales: 5,
    total: 51.5,
    avgTicket: 10.3,
    goal: 200,
    payments: [
      { id: 'dinheiro', label: 'Dinheiro', total: 24.0, count: 2, color: 'lime' },
      { id: 'credito', label: 'Crédito',  total: 24.0, count: 2, color: 'violet' },
      { id: 'debito',  label: 'Débito',   total: 3.5,  count: 1, color: 'sky' },
      { id: 'pix',     label: 'PIX',      total: 0,    count: 0, color: 'cyan' },
    ],
  },
  categories: [
    { id: 'top',       label: 'Mais vendidos' },
    { id: 'servicos',  label: 'Serviços' },
    { id: 'papelaria', label: 'Papelaria' },
    { id: 'pagamentos',label: 'Contas & boletos' },
    { id: 'todos',     label: 'Todos' },
  ],
  products: [
    // serviços (top)
    { id: 'p01', name: 'Impressão Web / WhatsApp',         price: 2.50, cat: 'servicos',   top: true,  icon: 'print',  badge: null },
    { id: 'p02', name: 'Impressão Web / WhatsApp parcial', price: 1.00, cat: 'servicos',   top: true,  icon: 'print',  badge: null },
    { id: 'p03', name: 'Cópia preto e branco',             price: 0.50, cat: 'servicos',   top: true,  icon: 'copy',   badge: null },
    { id: 'p04', name: 'Digitalização',                    price: 1.50, cat: 'servicos',   top: true,  icon: 'scan',   badge: null },
    { id: 'p05', name: 'Cópia colorida',                   price: 1.50, cat: 'servicos',   top: true,  icon: 'copy',   badge: null },
    { id: 'p06', name: 'Impressão colorida A4',            price: 2.00, cat: 'servicos',   top: true,  icon: 'print',  badge: null },
    { id: 'p07', name: 'Plastificação A4',                 price: 4.00, cat: 'servicos',   top: false, icon: 'shield', badge: null },
    { id: 'p08', name: 'Encadernação espiral',             price: 6.00, cat: 'servicos',   top: false, icon: 'book',   badge: null },
    // contas / boletos
    { id: 'p09', name: 'Segunda via Coelba / Embasa',      price: 2.50, cat: 'pagamentos', top: true,  icon: 'bolt',   badge: null },
    { id: 'p10', name: 'Atualização de boletos',           price: 2.50, cat: 'pagamentos', top: true,  icon: 'doc',    badge: null },
    { id: 'p11', name: 'Pagamento de conta',               price: 3.00, cat: 'pagamentos', top: false, icon: 'doc',    badge: null },
    // papelaria
    { id: 'p12', name: 'Contrato de locação Tilibra',      price: 1.00, cat: 'papelaria',  top: true,  icon: 'doc',    badge: '88 un' },
    { id: 'p13', name: 'Papel foto A4 180g',               price: 8.00, cat: 'papelaria',  top: true,  icon: 'paper',  badge: '24 un' },
    { id: 'p14', name: 'Caneta BIC azul',                  price: 1.50, cat: 'papelaria',  top: false, icon: 'pen',    badge: '120 un' },
    { id: 'p15', name: 'Cartucho HP 664 preto',            price: 65.00,cat: 'papelaria',  top: false, icon: 'box',    badge: '4 un' },
    { id: 'p16', name: 'Resma A4 500fls',                  price: 32.00,cat: 'papelaria',  top: false, icon: 'paper',  badge: '12 un' },
  ],
  recentSales: [
    { id: 207, customer: 'Consumidor',         method: 'credito',  total: 24.0, time: '10:44' },
    { id: 206, customer: 'Maria Aparecida',    method: 'dinheiro', total: 4.0,  time: '10:28' },
    { id: 205, customer: 'Consumidor',         method: 'dinheiro', total: 7.5,  time: '09:49' },
    { id: 204, customer: 'João Pedro Lima',    method: 'dinheiro', total: 2.5,  time: '09:42' },
    { id: 203, customer: 'Consumidor',         method: 'debito',   total: 3.5,  time: '09:40' },
    { id: 202, customer: 'Consumidor',         method: 'pix',      total: 12.0, time: '09:18' },
  ],
  paymentMethods: [
    { id: 'dinheiro',  label: 'Dinheiro',  shortcut: 'F1', icon: 'cash',   color: 'lime'   },
    { id: 'pix',       label: 'PIX',       shortcut: 'F2', icon: 'pix',    color: 'cyan'   },
    { id: 'debito',    label: 'Débito',    shortcut: 'F3', icon: 'card',   color: 'sky'    },
    { id: 'credito',   label: 'Crédito',   shortcut: 'F4', icon: 'card',   color: 'violet' },
    { id: 'boleto',    label: 'Boleto',    shortcut: 'F5', icon: 'doc',    color: 'amber'  },
    { id: 'crediario', label: 'Crediário', shortcut: 'F6', icon: 'wallet', color: 'rose'   },
  ],
  shortcuts: [
    { keys: ['F8'],     label: 'Cancelar item' },
    { keys: ['F10'],    label: 'Finalizar venda' },
    { keys: ['Esc'],    label: 'Limpar busca' },
    { keys: ['Enter'],  label: 'Adicionar bipado' },
    { keys: ['F2'],     label: 'Buscar cliente' },
    { keys: ['F7'],     label: 'Aplicar desconto' },
  ],
};
